export const img_car = require('./img_car.png');
export const img_bg_auth = require('./img_bg_auth.png');
export const img_car_2 = require('./img_car_2.png');
export const img_mall = require('./img_mall.png');
export const img_beach = require('./img_beach.png');
// export const ArticleImage1 = require('./ArticleImage1.png');
// export const ArticleImage2 = require('./ArticleImage2.png');
// export const ArticleImage3 = require('./ArticleImage3.png');
// export const ArticleImage4 = require('./ArticleImage4.png');